# clean base image containing only comfyui, comfy-cli and comfyui-manager
FROM runpod/worker-comfyui:5.8.4-base

# build-time tokens for gated downloads — never baked into final image.
# pass via: docker build --build-arg HF_TOKEN=$HF_TOKEN ...
ARG HF_TOKEN=""

# install custom nodes into comfyui
RUN git clone https://github.com/Fannovel16/comfyui_controlnet_aux /comfyui/custom_nodes/comfyui_controlnet_aux && cd /comfyui/custom_nodes/comfyui_controlnet_aux && (git checkout cc6b232f4a47f0cdf70f4e1bfa24b74bd0d75bf1 2>/dev/null || (git fetch origin cc6b232f4a47f0cdf70f4e1bfa24b74bd0d75bf1 --depth=1 && git checkout cc6b232f4a47f0cdf70f4e1bfa24b74bd0d75bf1) || echo "WARN: commit cc6b232f4a47f0cdf70f4e1bfa24b74bd0d75bf1 unreachable in https://github.com/Fannovel16/comfyui_controlnet_aux, falling back to default branch HEAD")
RUN git clone https://github.com/rgthree/rgthree-comfy /comfyui/custom_nodes/rgthree-comfy && cd /comfyui/custom_nodes/rgthree-comfy && (git checkout dbc5fa5e89b6a8b6a1a1dda787505b690f18026c 2>/dev/null || (git fetch origin dbc5fa5e89b6a8b6a1a1dda787505b690f18026c --depth=1 && git checkout dbc5fa5e89b6a8b6a1a1dda787505b690f18026c) || echo "WARN: commit dbc5fa5e89b6a8b6a1a1dda787505b690f18026c unreachable in https://github.com/rgthree/rgthree-comfy, falling back to default branch HEAD")
RUN git clone https://github.com/yolain/ComfyUI-Easy-Use /comfyui/custom_nodes/ComfyUI-Easy-Use && cd /comfyui/custom_nodes/ComfyUI-Easy-Use && (git checkout 3f37ba9491fa7f6c8520dda6cf92a8e2dcbee8fa 2>/dev/null || (git fetch origin 3f37ba9491fa7f6c8520dda6cf92a8e2dcbee8fa --depth=1 && git checkout 3f37ba9491fa7f6c8520dda6cf92a8e2dcbee8fa) || echo "WARN: commit 3f37ba9491fa7f6c8520dda6cf92a8e2dcbee8fa unreachable in https://github.com/yolain/ComfyUI-Easy-Use, falling back to default branch HEAD")

# download models into comfyui
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_2509_fp8_e4m3fn.safetensors' --relative-path models/diffusion_models --filename 'qwen_image_edit_2509_fp8_e4m3fn.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors' --relative-path models/text_encoders --filename 'qwen_2.5_vl_7b_fp8_scaled.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors' --relative-path models/vae --filename 'qwen_image_vae.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-4steps-V1.0.safetensors' --relative-path models/loras --filename 'Qwen-Image-Lightning-4steps-V1.0.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-8steps-V2.0-bf16.safetensors' --relative-path models/loras --filename 'Qwen-Image-Lightning-8steps-V2.0-bf16.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/anhcv90/sketch_line_art_darkbg_000002400/resolve/main/sketch_line_art_darkbg_000002400.safetensors' --relative-path models/loras --filename 'sketch_line_art_darkbg_000003600.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done

# copy all input data (like images or videos) into comfyui (uncomment and adjust if needed)
# COPY input/ /comfyui/input/

# user-provided inputs override the auto-generated placeholders above.
RUN wget --progress=dot:giga -O '/comfyui/input/7030545 (1).jpeg' "https://cool-anteater-319.convex.cloud/api/storage/e7a2e548-8474-43f0-80ad-f6d42a5859fa"
RUN wget --progress=dot:giga -O '/comfyui/input/20260609-120038.jpg' "https://cool-anteater-319.convex.cloud/api/storage/f8535836-6f1d-413e-833b-bd43208975cc"
